services:
  sscs-base:
    image: sscs-base
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/workspace
    environment:
      - GITHUB_AUTH_TOKEN=${GH_AUTH_TOKEN}

  python:
    image: python-security
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/workspace
    environment:
      - GITHUB_AUTH_TOKEN=${GH_AUTH_TOKEN}

  rust:
    image: rust-security
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/workspace
    environment:
      - GITHUB_AUTH_TOKEN=${GH_AUTH_TOKEN}

  node:
    image: node-security
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/workspace
    environment:
      - GITHUB_AUTH_TOKEN=${GH_AUTH_TOKEN}

  go:
    image: go-security
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/workspace
    environment:
      - GITHUB_AUTH_TOKEN=${GH_AUTH_TOKEN}
